apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-quarkus
  namespace: todo-project-jenkins
spec:
  selector:
    matchLabels:
      app: todo-api-quarkus
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-api-quarkus
    spec:
      paused: true
      serviceAccountName: todo-api-quarkus
      containers:
        - name: todo-api-quarkus
          image: todo-api-quarkus
          ports:
            - containerPort: 8080
          env:
            - name: APP_STAGE_NAME
              valueFrom:
                configMapKeyRef:
                  name: todo-api-quarkus
                  key: app.stage-name
