apiVersion: v1
kind: Service
metadata:
  name: todo-api-quarkus
  namespace: todo-project-jenkins
spec:
  selector:
    app: todo-api-quarkus
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
